name: CI
on:
  push:
    branches: [master]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [
          14.x
        ]
    steps:
    - uses: actions/checkout@v1
    - name: Select node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: yarn install
    - name: Run tests
      run: yarn test
      env:
        CI: true
